### ISSUE TITLE
SDL Editor Provokes Frequent Parsing Errors

### ISSUE THREAD

**Issue by chainzero** [akash-network/console#1065]
Receiving frequent errors when attempting to use SDL editor screen in Console.

Example:

- Create new deployment
- Select Run Custom Container
- Enter YAML tab
- Select all text in editor > delete >  copy in SDL of interest
- Attempt to copy/paste SDL results in the following error

```
Error
Cannot read properties of undefined (reading 'resources')
```

Errors attempting to edit SDL are not unique to above, example flow.  Receive similar errors in attempting to use a template from Awesome Akash and when editing the SDL in that flow.

**Comment by chainzero** [comment]
SDL used in testing cited example if useful:

```
---
version: "2.0"

services:
  obtaingpuone:
    image: ubuntu:22.04
    command:
      - "sh"
      - "-c"
    args:
      - 'uptime;
        nvidia-smi;
        sleep infinity'
    expose:
      - port: 8080
        as: 80
        to:
          - global: true

profiles:
  compute:
    obtaingpu:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 256Mi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
        storage:
          size: 256Mi
  placement:
    akash:
      pricing:
        obtaingpu: 
          denom: uakt
          amount: 10000000

deployment:
  obtaingpuone:
    akash:
      profile: obtaingpu
      count: 1
```
