### ISSUE TITLE
Console UI strips custom provider attribute values (e.g., `testissue`) from `MsgCreateDeployment` TX

### ISSUE THREAD

**Issue by ghost** [akash-network/console#1133]
When deploying via the Akash Console, the `MsgCreateDeployment` transaction omits or strips certain custom provider attribute values defined in the SDL.

---

#### **Steps to Reproduce:**

1. Navigate to: [`Deploy` -> `Upload your SDL`](https://console.akash.network/new-deployment?step=edit-deployment)
2. Upload the following SDL (Load it from file stored on your local disk):

```yaml
---
version: "2.0"

services:
  tetris:
    image: bsord/tetris
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      # SSH port
      - port: 22
        as: 22
        to:
          - global: true

profiles:
  compute:
    tetris:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 2Gi
        storage:
          - size: 2Gi
  placement:
    akash:
      attributes:
        host: akash
        testissue: 300
      #  datacenter: us-midwest-qci-1
      #  #organization: overclock
      pricing:
        tetris:
          denom: uakt
          amount: 1000000

deployment:
  tetris:
    akash:
      profile: tetris
      count: 1
```

3. Confirm that the SDL is correctly displayed in the UI:
   ![Console UI Preview](https://github.com/user-attachments/assets/4d240ce2-e8e5-4896-8c20-178c1049554f)

4. Complete the deployment and inspect the resulting transaction.

---

#### **Expected Result (Using CLI):**

When deployed using `provider-services` CLI `v0.6.10`, the attribute is preserved as expected:

```bash
$ provider-services query tx EC626B3980964D4341B23C7DFED5AD84A76F60B38FDB6C44390F3A035935F63E | grep -B3 -A1  'key: testissue'
          attributes:
          - key: host
            value: akash
          - key: testissue
            value: "300"
```

---

#### **Actual Result (Using Console):**

When deploying the same SDL through the Console, the attribute is present but the value is **stripped**:

```bash
$ provider-services query tx BB003122B3CC290E339E2FF1CB91C0084E9EB42EEDD9A2961A791B2B0B3C038A | grep -B3 -A1  'key: testissue'
          attributes:
          - key: host
            value: akash
          - key: testissue
            value: ""
```

---

#### **Conclusion:**

The Console UI appears to be incorrectly handling custom provider attributes — specifically removing or failing to retain their values when preparing the deployment transaction. This results in unexpected behavior and inconsistency with CLI-based deployments.
