### ISSUE TITLE
Shell is not accessible when shm is enabled.

### ISSUE THREAD

**Issue by kyoungbinkim** [akash-network/console#1138]
I follwed  https://akash.network/docs/getting-started/stack-definition-language/#shared-memory-shm  and https://gist.github.com/chainzero/0dea9f2e1c4241d2e4d490b37153ec86 page. I've tried multiple providers, but they didn't work. 

 
No connection to SHELL.
 

Below is my SDL
```
---
version: "2.0"
services:
  service-1:
    image: ubuntu:22.04
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    params:
      storage:
        shm:
          mount: /dev/shm
    command:
      - bash
      - "-c"
    args:
      - >-
        apt-get update;apt-get install nano; sleep infinity
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 12
        memory:
          size: 32Gb
        storage:
          - size: 40Gi
          - name: shm
            size: 2Gi
            attributes:
              persistent: false
              class: ram
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: p100
                - model: v100
                - model: rtxa6000
                - model: rtx3070
                - model: rtx3060
                - model: rtx3090
                - model: rtx8000
                - model: rtx4090
                - model: t4
                - model: a6000
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 10000

deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1


```

![Image](https://github.com/user-attachments/assets/4db2fb60-2b23-435f-84a3-e1af53cc05f9)

![Image](https://github.com/user-attachments/assets/b3d59935-cdee-462d-a5cc-4f26da209fd4)
