### ISSUE TITLE
Implement new 'ram' storage class

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#131]
There is a new storage class called ram . it must not be persistent. SDL parser should error if it is persistent. This is only change to the SDL.
Provider must declare ram class as supported in it’s provider attributes (note persistent is set to false)
```
  - key: capabilities/storage/3/class
    value: ram
  - key: capabilities/storage/3/persistent
    value: false
```
Provider bid script (if used must declare support for ram storage class and use it in pricing strategy. I’ll have link to reference script shortly
SDL

```
---
version: "2.0"

services:
  grafana:
    image: grafana/grafana
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
        accept:
          - webdistest.localhost
    params:
      storage:
        data:
          mount: /var/lib/grafana
        shm:
          mount: /dev/shm
profiles:
  compute:
    grafana:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 512Mi
          - name: data
            size: 1Gi
            attributes:
              persistent: true
              class: beta2
          - name: shm
            size: 1Gi
            attributes:
              class: ram
  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        grafana:
          denom: uakt
          amount: 1000
deployment:
  grafana:
    westcoast:
      profile: grafana
      count: 1
```
