### ISSUE TITLE
Issue pulling private docker repo

### ISSUE THREAD

**Issue by maxmillionbeatz** [akash-network/console#151]
Is there any *secure* way to pull a private docker repo? Can we store secrets with cloudmos securely?

For example:
```
---
version: "2.0"
services:
  service-1:
    image: user/someimage
    - credentials
      - username: user
      - password: <reference to secretly stored password> 
    ....
```
