### ISSUE TITLE
Error saving template

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#76]
when trying to import and save this sdl to my templates on my cloudmos profile.
i get this error.

```
---
version: "2.0"

services:
  geekbench:
    image: davidsarkany/geekbench:6.0.2
    expose:
      - port: 80
        to:
          - global: true
    env:
      - GEEKBENCH_VERSION=6.0.2 #Supports any version of 5.0
      - UPLOAD #Replace with NO_UPLOAD to disable uploading results to the Geekbench Browser
      #- EMAIL= #Unlock Geekbench using EMAIL and KEY
      #- KEY= #Required if email is present
profiles:
  compute:
    geekbench:
      resources:
        cpu:
          units: 250
        memory:
          size: 100Gi #2Gi required
        storage:
          size: 100Gi
  placement:
    akash:
      pricing:
        geekbench:
          denom: uakt
          amount: 10000
deployment:
  geekbench:
    akash:
      profile: geekbench
      count: 1
```

![image](https://github.com/akash-network/cloudmos/assets/15185355/16c81a22-ce3d-4824-9f24-715a79130a04)
